### ISSUE TITLE
password to access

### ISSUE THREAD

**Issue by berimbauesam** [diddlesnaps/tvheadend#2]
First thanks for the snap script. 
I have installed and it is running. But I do not have access to web admin area because i do not know the password.

**Comment by diddledan** [comment]
The password is set the first time you access the web interface by going through the wizard. Once it is set you can only change it from the web interface. If you have locked yourself out of the interface you can reset tvheadend to re-run the wizard by removing the snap and reinstalling anew. Alternatively you can do it manually by removing all files in `/var/snap/tvheadend/current/accesscontrol` and create a new file there called `cd8d0804bef721c2cadef68e5ba6e44e` with the following content (this is done automatically when you first install the snap):

```json
{
        "index": 1,
        "enabled": true,
        "username": "*",
        "prefix": "0.0.0.0/0,::/0",
        "change": [
                "change_rights"
        ],
        "uilevel": -1,
        "uilevel_nochange": -1,
        "streaming": [
                "basic",
                "advanced",
                "htsp"
        ],
        "profile": [
        ],
        "dvr": [
                "basic",
                "htsp",
                "all",
                "all_rw",
                "failed"
        ],
        "htsp_anonymize": false,
        "dvr_config": [
        ],
        "webui": true,
        "admin": true,
        "conn_limit_type": 0,
        "conn_limit": 0,
        "channel_min": 0,
        "channel_max": 0,
        "channel_tag_exclude": false,
        "channel_tag": [
        ],
        "comment": "Default access entry",
        "wizard": false
}
```

**Comment by john3voltas** [comment]
Hi there.
I am having issues with tvheadend snap.
I've installed the snap, went all through the wizard, chose the 'admin' and 'user' usernames and passwords and when the wizard finishes setting everything up and I try to login it simply won't work.
No error message. It just asks me the username and password all over and over again.
I have already gone to remove the package and reinstall.
The second time around I even chose different usernames and different passwords.
It just won't work...
Any tips for me?
Thanks in advance.
Cheers

**Comment by diddledan** [comment]
TVHeadend is picky about the password but doesn't enforce those picky rules so it is possible you have saved a password that it is unable to match. I have found this when I included a hyphen `-` in my password, though it might be because I included it as the last character. I don't know what the rules are or why they're important.

I suggest you try a simple password to begin with, maybe only letters, then create another user account to test more complex passwords before you commit the more complex password to your admin account.

**Comment by john3voltas** [comment]
@diddledan 
Thanks for the tip about the special characters.
I think my password doesn't include anything besides A-Z, a-z, 0-9 but I may have included an exclamation mark.

Still, right now I don't know how I can re-run the initial wizard. AFAIK to re-run the wizard and pick another password I would have to be able to log into the webUI and right now I can't because the current password is borked...
What can I do to factory default the snap? Do I really need to reinstall?
TIA
Cheers

**Comment by diddledan** [comment]
My first comment in this issue tells you how to do it.

**Comment by john3voltas** [comment]
Hi @diddledan 
I'm still having issues after the setup wizard.
This time I uninstalled/reinstalled the snap, rerun the wizard and chose admin user 'htsadmin' and password 'htspass123' but at the end of the wizard I still can't login.
I don't get it...what am I doing wrong here?
TIA
Cheers

**Comment by diddledan** [comment]
I'm really sorry that you're having trouble. I don't know what the problem can be, but I'll do some experiments to see if I can replicate this and potentially fix it :-(

**Comment by john3voltas** [comment]
Darned. Do you think there's any debugging that I could do on my end?
Any log I should be checking?
I am more than willing to help you help me, I'm just not sure how.
Hey, maybe I could try installing TVH through the package manager and see if it does the same thing.
And I'm gonna check the project bug tracker to see if I find something similar.
Cheers

**Comment by john3voltas** [comment]
@diddledan 
Thanks a bunch for your help.
I've just been able to make it work for me.
I changed the password not to include part of the username AND I enabled access not only from my subnet 10.11.11.0/24 but to every subnet 0.0.0.0/0
It's down to either one of those or a mix of both.
I feel more inclined to go with the latter. Please bear in mind that I was trying to run the wizard from within the same computer where I was installing the snap.
To access the webUI I would access http://127.0.0.1:9981 and it would ask me for the password.
I would expect it to not even ask me for a password if my client was not on the same subnet as the whitelist setup during the wizard...
But that's got nothing to do with you or with your snap.
So thanks a bunch for your help and for putting up the work to create and maintain this snap.
Cheers

**Comment by diddledan** [comment]
aha. good diagnostics! I forgot all about that feature. I believe that you can input multiple addresses/networks, so you could possibly try using `10.11.11.0/24,127.0.0.1`.

**Comment by john3voltas** [comment]
Ah! Not gonna risk loosing access to the webUI now. Gonna let it stay open to any subnet.
To be honest, in my particular case, I don't see much security improvement in blocking other subnets because I don't have other subnets. Right now, at least.
In the future, if I create an open WiFi network for our guest I will create a 2nd subnet and then I will want to secure the webUI of TVH.
Thanks for your tips, though.
Cheers

**Comment by diddledan** [comment]
I'll close this issue as it seems you're up and running now :-)
